const categories = {
  Travel: [
    "Flights",
    "Trains",
    "Buses",
    "Cabs/Ride-Sharing",
    "Vehicle Rentals",
    "Taxis",
    "Visas",
    "Tour Packages",
  ],
  Food: [
    "Breakfast",
    "Lunch",
    "Dinner",
    "Snacks",
    "Desserts",
    "Beverages",
    "Takeout/Delivery",
    "Meal Prep Ingredients",
    "Dietary Supplements",
    "Meal Kits",
  ],
  Shopping: [
    "Clothes",
    "Electronics",
    "Home Goods",
    "Accessories",
    "Gifts",
    "Personal Care Products",
    "Online Shopping",
    "Sales/Discounts",
  ],
  Medical: [
    "Doctor's Visits",
    "Medications",
    "Health Check-ups",
    "Vaccinations",
    "Medical Equipment",
    "Lab Tests",
    "Emergency Services",
    "Counseling",
    "Physical Therapy",
  ],
  Housing: [
    "Rent/Mortgage",
    "Maintenance/Repairs",
    "Security Deposits",
    "Home Improvements",
    "Home Repairs",
    "Home Appliances",
    "Real Estate Agent Fees",
  ],
  PGs_Leasing: [
    "Rent",
    "Security Deposit",
    "Maintenance",
    "Furnishing",
    "Lease Agreement Fees",
    "PG Facility Fees",
  ],
  Bills: [
    "Phone Bill",
    "Cable/Satellite TV",
    "Trash Collection",
    "Subscription Services",
    "Internet Service Provider Fees",
  ],
  Study_Stationeries: [
    "Notebooks",
    "Pens/Pencils",
    "Textbooks",
    "Highlighters",
    "Binders",
    "Erasers",
    "Markers",
    "Calculator",
  ],
  Entertainment: [
    "Movies/TV Shows",
    "Concerts/Events",
    "Video Games",
    "Sports Events",
    "Museums/Exhibitions",
  ],
  Utilities: ["Heating/Cooling", "Trash Removal", "Sewer Charges"],
  Transportation: [
    "Public Transit",
    "Car Maintenance",
    "Parking Fees",
    "Vehicle Insurance",
    "Tolls",
  ],
  Fitness: [
    "Gym Membership",
    "Fitness Classes",
    "Personal Training",
    "Home Workout Equipment",
    "Yoga/Meditation Classes",
    "Athletic Wear",
    "Sports Club Memberships",
    "Fitness Equipment",
  ],
  Personal_Care: [
    "Haircuts/Styling",
    "Skincare Products",
    "Makeup",
    "Toiletries",
    "Nail Care",
    "Dental Care",
    "Grooming Supplies",
    "Hair Treatment Products",
    "Cosmetics",
    "Spa Treatments",
  ],
  Education: [
    "Tuition Fees",
    "Online Courses",
    "Workshops/Seminars",
    "Certifications",
    "Study Materials",
    "Exam Fees",
    "Language Learning",
    "Test Preparation",
  ],
  Subscriptions: [
    "Magazines/Journals",
    "Software",
    "News Services",
    "Membership Clubs",
    "Apps/Online Tools",
  ],
  Gifts: [
    "Birthday Gifts",
    "Holiday Gifts",
    "Anniversary Gifts",
    "Thank You Gifts",
    "Special Occasion Gifts",
    "Personalized Gifts",
    "Gift Cards",
  ],
  Childcare: [
    "Daycare/Preschool",
    "Babysitting",
    "Children's Activities/Classes",
    "School Supplies",
    "Clothing",
    "Health Care",
    "Toys/Games",
  ],
  Insurance: [
    "Health Insurance",
    "Life Insurance",
    "Auto Insurance",
    "Travel Insurance",
    "Property Insurance",
    "Business Insurance",
    "Dental Insurance",
    "Disability Insurance",
  ],
  Home_Improvement: [
    "Renovations",
    "Painting",
    "Furniture",
    "Landscaping",
    "DIY Projects",
    "Appliances",
    "Decorating",
    "Roofing",
    "Plumbing",
    "Electrical Repairs",
  ],
  Hobbies: [
    "Craft Supplies",
    "Musical Instruments",
    "Art Supplies",
    "Gardening",
    "Photography",
    "Collectibles",
  ],
  Pets: [
    "Food",
    "Veterinary Care",
    "Grooming",
    "Toys",
    "Training",
    "Pet Insurance",
    "Boarding/Daycare",
  ],
  Savings_Investments: [
    "Emergency Fund",
    "Retirement Contributions",
    "Mutual Funds",
    "Stocks/Bonds",
    "Fixed Deposits",
    "Cryptocurrency",
  ],
  Loans_Debts: [
    "Credit Card Payments",
    "Student Loan Payments",
    "Personal Loan EMI",
    "Mortgage EMI",
    "Car Loan EMI",
  ],
  Legal_Documentation: ["Lawyer Fees", "Notary Fees", "Government Documents"],
  Professional_Expenses: [
    "Tools/Equipment",
    "Office Supplies",
    "Remote Work Setup",
    "Co-working Space Fees",
  ],
  Events_Celebrations: [
    "Party Expenses",
    "Event Decoration",
    "Venue Booking",
    "Catering",
  ],
  Religious_Spiritual: ["Temple Donations", "Pooja Items", "Ritual Services"],
  Laundry_Cleaning: [
    "Laundry Service",
    "Detergents & Cleaning Supplies",
    "House Cleaning Service",
  ],
  Common_Daily_Needs: [
    "Books",
    "Groceries",
    "Electricity",
    "Water",
    "Gas",
    "Internet",
    "Fuel",
    "Property Taxes",
    "Home Insurance",
    "Streaming Services",
    "Sports Equipment",
  ],
};

export default categories;
